export const TRIGGER = "trigger"
export const ACTION = "action"
export const COMMENT = "comment"
export const T_COLOR = "#e87968"
export const A_COLOR = "#ffcd59"
export const C_COLOR = "#c4bfb5"
export const D_COLOR = "#a0eb91"
